#根据ibaq对功能分布进行分析
cog<-read.table("COG_sample_sc.txt",header=TRUE,sep="\t")
Sample<-c("S08","S10","S12","S14","S16","S18","S20","S22","S24","S26","S28")
sc<-data.frame(cog,row.names = 1)
sc1<-t(sc)
sc1<-as.data.frame(sc1,row.names = F)
sc2<-as.data.frame(cbind(Sample,sc1))
library(reshape2)
sc3<-melt(sc2,id = "Sample")
head(sc3)
Category<-c(rep(c("Metabolism"),11),rep(c("Cell Process & Signaling"),11),rep(c("Metabolism"),55),rep(c("Information Storage & Processing"),33),rep(c("Cell Process & Signaling"),33),rep(c("Metabolism"),22),rep(c("Poorly Characterized"),22),rep(c("Cell Process & Signaling"),33))
new3<-cbind(sc3,Category)
colnames(new3)<-c("Sample","COG","Spectra","Category")
library(ggplot2)
ggplot(new3, aes(x=factor(COG), y=Spectra))+geom_boxplot(aes(fill=Category))+xlab("COG")+ylab("Percent of Spectra")
