a<-read.table("Species_Abundance.txt",header = T, sep = "\t")
Sample<-c("S08","S10","S12","S14","S16","S18","S20","S22","S24","S26","S28")
c1<-data.frame(a,row.names = 1)
c2<-t(c1)
c1<-as.data.frame(c2,row.names = F)
c2<-cbind(Sample,c1)
group<-c(rep(c("East"),5),rep(c("West"),6))
c4<-cbind(c2,group)
east<-a[,c(1:6)]
west<-a[c(1,7,8,9,10,11,12)]
library(MASS)
wilcox.test(c4$Alphaproteobacteria ~ c4$group)
wilcox.test(c4$Acidithiobacillia ~ c4$group)
wilcox.test(c4$Actinobacteria ~ c4$group)
wilcox.test(c4$Bacteroidetes ~ c4$group)
wilcox.test(c4$Betaproteobacteria ~ c4$group)
wilcox.test(c4$`Candidatus Kryptonia` ~ c4$group)
wilcox.test(c4$Chloroflexi ~ c4$group)
wilcox.test(c4$Cyanobacteria ~ c4$group)
wilcox.test(c4$`Candidatus Marinimicrobia` ~ c4$group)
wilcox.test(c4$Deferribacteres ~ c4$group)
wilcox.test(c4$Verrucomicrobia ~ c4$group)
wilcox.test(c4$Planctomycetes ~ c4$group)
wilcox.test(c4$`Other Proteobacteria` ~ c4$group)
wilcox.test(c4$Deltaproteobacteria ~ c4$group)
wilcox.test(c4$Gammaproteobacteria ~ c4$group)
wilcox.test(c4$`Candidatus Peregrinibacteria` ~ c4$group)
wilcox.test(c4$`Candidatus Peribacteria` ~ c4$group)
wilcox.test(c4$`Deinococcus-Thermus` ~ c4$group)
wilcox.test(c4$Spirochaetes ~ c4$group)
wilcox.test(c4$Chlorobi ~ c4$group)
wilcox.test(c4$`unclassified Bacteria` ~ c4$group)
wilcox.test(c4$Thermodesulfobacteria ~ c4$group)
wilcox.test(c4$Firmicutes ~ c4$group)
wilcox.test(c4$Gemmatimonadetes ~ c4$group)
wilcox.test(c4$Ignavibacteriae ~ c4$group)
wilcox.test(c4$Nitrospirae ~ c4$group)
wilcox.test(c4$Rhodothermaeota ~ c4$group)
wilcox.test(c4$Thermotogae ~ c4$group)
